.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GPAR2 1 "February 27, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gpar2 0.3 \- GUI for PAR and PAR2 sets
.SH SYNOPSIS
.B gpar2
[options]
.br
.B gpar2
[options]
.I filename..
.SH DESCRIPTION
This manual page documents briefly the
.B gpar2
program.
.PP
.B gpar2
is a GUI utilizing the
.B libpar2
library and allows to verify and repair PAR and PAR2 recovery sets,
and provides semi-detailed output of the process.
.PP
.SH OPTIONS
Program options and usage:
.TP
.B gpar2
.br
Open the GUI
.TP
.B gpar2 /foo/bar
Open the GUI and check
.B foo
in the directory
.B bar
for errors.
.SH SEE ALSO
.BR libpar2 (1),
.BR par2cmdline (1),
.BR parcmdline (1).
.PP
These are common programs also related to PAR and PAR2 sets.
.SH AUTHOR
gpar2 was written by Francois Lesueur and John Augustine.
.PP
This manual page was written by John Augustine <jaugustine@vivnet.net>,
for the Ubuntu project (but may be used by others).
